### PR TITLE
Add NTAG Bindings & run rustfmt

### PR DESCRIPTION
**Pull request by 0xbe7a**
Hello ive added bindings to the ntag* functions. Ive also added them to the freefare package, but since ive fixed the ffi:: stuff in the freefare package to acctually use freefare-sys, you will need to merge this first.

### CODE REVIEW

**Comment by dsgriffin** [comment]
Thanks!

**Comment by 0xbe7a** [comment]
can you bump the version and push it to crates.io, so i can create a PR for freefare?

**Comment by dsgriffin** [comment]
@0xBE7A done

**Comment by dsgriffin** [comment]
@0xBE7A done!

**Pull request merged**
